---
id: Http
name: Http
full: HTTP client library
description: A library for making HTTP requests.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Http
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/support: ^3
      psr/http-message: ^1
      psr/http-factory: ^1
      psr/http-client: ^1
  optional:
    composer:
      horde/test: ^3
    ext:
      curl: '*'
      http: '*'
